# Generated by Django 2.2.6 on 2020-10-25 19:54

import aplications.rentalProperty.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rentalProperty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, upload_to=aplications.rentalProperty.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 10, 25, 19, 54, 28, 533391, tzinfo=utc)),
        ),
    ]
